### ISSUE TITLE
Add syntax checker

### ISSUE THREAD

**Issue by PrivateGER** [PerhapsSomeone/GreenLight#13]
Implement a syntax checker that works. The current one is very situational and barely does anything at all. 

Take a look at lib/syntax_checker.js for an idea of how to implement syntax checking functions.
You may introduce breaking changes into the project, but I would prefer it if you could keep them as smooth as possible. 

This issue will likely require modification of the transpiler. It is located in lib/transpiler.js.

**Comment by klee214** [comment]
Hello! I can give a little help to enhance your program. 
I will try to add some great syntax checker features!
